project_name = "My First Project"
project_id = "myfirstproject"
project_author = "Manuel Bernal Llinares"
project_author_email = "mbdebian@gmail.com"
project_contact_email = "mbdebian@gmail.com"
s3_devops_prefix = "mbdebiandevops"
s3_region = "us-east-1"